[package]
name = "kitchensink-runtime"
version = "3.0.0-dev"
authors.workspace = true
description = "Substrate node kitchensink runtime."
edition.workspace = true
build = "build.rs"
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# third-party dependencies
codec = { features = ["derive", "max-encoded-len"], workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
sp-debug-derive = { workspace = true, features = ["force-debug"] }
static_assertions = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }

# Core Substrate dependencies
frame-support = { workspace = true, features = ["tuples-96"] }
frame-system = { workspace = true, features = ["std"] }
frame-executive = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
sp-std = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std", "wasm_only"] }
sp-api = { workspace = true, features = ["std"] }
sp-block-builder = { workspace = true, features = ["std"] }
sp-inherents = { workspace = true, features = ["std"] }
sp-version = { workspace = true, features = ["std"] }
sp-weights = { workspace = true, features = ["std"] }
sp-storage = { workspace = true, features = ["std"] }
sp-trie = { workspace = true, features = ["std"] }
sp-state-machine = { workspace = true, features = ["std"] }
sp-externalities = { workspace = true, features = ["std"] }
sp-timestamp = { workspace = true, features = ["std"] }

# Pallet dependencies
pallet-balances = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
pallet-sudo = { workspace = true, features = ["std"] }

# shared code between runtime and node
node-primitives = { path = "../primitives", default-features = false }

[build-dependencies]
substrate-wasm-builder = { workspace = true }
substrate-build-script-utils = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "frame-executive/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-std/std",
    "sp-io/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-inherents/std",
    "sp-version/std",
    "sp-weights/std",
    "sp-storage/std",
    "sp-trie/std",
    "sp-state-machine/std",
    "sp-externalities/std",
    "sp-timestamp/std",
    "pallet-balances/std",
    "pallet-timestamp/std",
    "pallet-sudo/std",
    "node-primitives/std",
    "scale-info/std",
    "sp-debug-derive/std"
]

runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-sudo/runtime-benchmarks"
]

try-runtime = [
    "frame-executive/try-runtime",
    "frame-system/try-runtime",
    "pallet-balances/try-runtime",
    "pallet-timestamp/try-runtime",
    "pallet-sudo/try-runtime"
]